# Generated by rust2rpm 28
%bcond check 1

%global crate whattime

Name:           whattime
Version:        1.0.2
Release:        %autorelease
Summary:        See the current time at any time!

License:        GPL-3.0
URL:            https://crates.io/crates/whattime
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
See the current time at any time!.}

%description %{_description}

%files
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/whattime

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
