# Generated by rust2rpm 27 and modified
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

%global crate whattime

Name:           whattime
Version:        1.0.2
Release:        %autorelease
Summary:        See the current time at any time!

License:        GPL-3.0
URL:            https://crates.io/crates/whattime
Source:         %{crates_source}
Source:         %{name}-%{version}-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
See the current time at any time!.}

%description %{_description}

%files
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/whattime

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
